# Generated by Django 5.1.3 on 2024-11-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название основного поставщика', max_length=200, verbose_name='Поставщик')),
                ('url', models.URLField(blank=True, help_text='адрес', verbose_name='Адрес каталога с ценами')),
                ('email', models.EmailField(blank=True, help_text='Электронная почта для отправки заявки', max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, help_text='Контактный номер телефона поставщика', max_length=20, verbose_name='Номер телефона')),
                ('manager', models.CharField(blank=True, help_text='Имя персонального менеджера', max_length=200, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
