# Generated by Django 5.1.3 on 2024-11-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_suppliermodel_legal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermodel',
            name='email',
            field=models.EmailField(blank=True, help_text='адрес ', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='legal_name',
            field=models.CharField(blank=True, help_text='ИП или ООО', max_length=200, verbose_name='Юридическое наименование'),
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='name',
            field=models.CharField(help_text='Название в программе', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='url',
            field=models.URLField(blank=True, help_text='URL', verbose_name='Адрес каталога с ценами'),
        ),
    ]
