# Generated by Django 3.2 on 2024-10-08 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalulateRectangleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Дата расчета', null=True, verbose_name='Дата')),
                ('length', models.FloatField(help_text='По внутрянке', verbose_name='Длинна бассейна')),
                ('width', models.FloatField(help_text='по внутрянке', verbose_name='Ширина бассейна')),
                ('depth_from', models.FloatField(help_text='Перепад глубины не больше 10см на 1 метр', verbose_name='Глубина от')),
                ('depth_to', models.FloatField(help_text='В случае прямого дна поствить то же что и в Глубина от', verbose_name='Глубина до')),
                ('client', models.ForeignKey(blank=True, help_text='Не обязательно к заполнению', on_delete=django.db.models.deletion.CASCADE, to='clients.clientmodel', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Расчет',
                'verbose_name_plural': 'Расчет скиммерного прямоугольного бассейна',
            },
        ),
    ]
