# Generated by Django 3.2 on 2024-10-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_work_name',
            field=models.CharField(default=1, editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Работы по пленке отделке'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_work_price',
            field=models.FloatField(blank=True, default=1, editable=False, verbose_name='Стоимость работ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_work_summ',
            field=models.FloatField(blank=True, default=1, editable=False, verbose_name='Сумма за работы'),
            preserve_default=False,
        ),
    ]
