# Generated by Django 3.2 on 2024-10-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='volume',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Объем бассейна'),
        ),
    ]
