# Generated by Django 3.2 on 2024-10-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_auto_20241023_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_corner_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Работы по пленке отделке'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_corner_price',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Стоимость работ'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_corner_summ',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Сумма за работы'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_corner_unit_of_measurement',
            field=models.CharField(blank=True, default='', editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Работы по пленке отделке'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_glue_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Работы по пленке отделке'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_glue_price',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Стоимость работ'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_glue_summ',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Сумма за работы'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_glue_unit_of_measurement',
            field=models.CharField(blank=True, default='', editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Работы по пленке отделке'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_pvc_glue_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Работы по пленке отделке'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_pvc_glue_price',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Стоимость работ'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_pvc_glue_summ',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Сумма за работы'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_pvc_glue_unit_of_measurement',
            field=models.CharField(blank=True, default='', editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Работы по пленке отделке'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_textile_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Работы по пленке отделке'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_textile_price',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Стоимость работ'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_textile_summ',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Сумма за работы'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_textile_unit_of_measurement',
            field=models.CharField(blank=True, default='', editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Работы по пленке отделке'),
        ),
    ]
