# Generated by Django 3.2 on 2024-10-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_calulaterectanglemodel_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='filtration_speed',
            field=models.CharField(choices=[(30, '30 м/ч'), (20, '20 м/ч'), (10, '10 м/ч')], default=20, help_text='Чем ниже скорость тем качественнее очистка воды', max_length=20, verbose_name='Время полного водообмена'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='water_exchange_time',
            field=models.CharField(choices=[(6.0, '6 часов'), (4.0, '4 часа'), (2.0, '2 часа'), (1.0, '1 час'), (0.5, '30 минут')], default=6, help_text='Для частного бассейна необходимо 6 часов, для бассейнов в небольших гостиницах 4 часа', max_length=20, verbose_name='Время полного водообмена'),
        ),
    ]
