# Generated by Django 3.2 on 2024-10-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_auto_20241023_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='filters_price',
            field=models.FloatField(blank=True, default=0, editable=False, help_text='Заполняется из базы', verbose_name='Цена фильтра'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='filters_quality',
            field=models.IntegerField(blank=True, default=0, editable=False, help_text='Заполняется автоматически', verbose_name='Количество фильтров'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='filters_summ',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Сумма за фильтры'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_manetral_corner_qyality',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Количество материалов'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_manetral_glue_qyality',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Количество материалов'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_manetral_textile_qyality',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Количество материалов'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_manetral_work_qyality',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Количество материалов'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_material_pvc_glue_qyality',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='pumps_price',
            field=models.FloatField(blank=True, default=0, editable=False, help_text='Заполняется из базы', verbose_name='Цена насоса'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='pumps_quality',
            field=models.IntegerField(blank=True, default=0, editable=False, help_text='Заполняется автоматически', verbose_name='Количество насосов'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='pumps_summ',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Сумма за насосы'),
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='finished_material_corner_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Угол с напылением ПВХ'),
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='finished_material_corner_price',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Цена уголка с напылением ПВХ'),
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='finished_material_corner_summ',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Сумма за Угол с напылением ПВХ'),
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='finished_material_corner_unit_of_measurement',
            field=models.CharField(blank=True, default='', editable=False, help_text='Финишная отделка', max_length=200, verbose_name='единица измерения'),
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='finished_material_glue_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Клей геотекстиля'),
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='finished_material_glue_price',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='finished_material_glue_summ',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Сумма за клей'),
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='finished_material_glue_unit_of_measurement',
            field=models.CharField(blank=True, default='', editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Жидкий ПВХ'),
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='finished_material_textile_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Гео текстиль'),
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='finished_material_textile_price',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='цена за единицу'),
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='finished_material_textile_summ',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='сумма за геотекстиль'),
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='finished_material_textile_unit_of_measurement',
            field=models.CharField(blank=True, default='', editable=False, help_text='Финишная отделка', max_length=200, verbose_name='единица измерения'),
        ),
    ]
