# Generated by Django 3.2 on 2024-10-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0004_auto_20241008_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='area',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Площадь зеркала воды'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='filter_area',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Рекомендованная площадь фильтра'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='pump_power',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Рекомендованная мощность насоса'),
        ),
    ]
