# Generated by Django 3.2 on 2024-10-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0006_alter_calulaterectanglemodel_water_exchange_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='finished_materials',
            field=models.CharField(blank=True, editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Материал'),
        ),
    ]
