# Generated by Django 3.2 on 2024-10-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_filterelementmodel'),
        ('calculation', '0006_alter_calulaterectanglemodel_filter_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='filter_element',
            field=models.ForeignKey(blank=True, default='1', help_text='Выбрать из имеющегося', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.filterelementmodel', verbose_name='Фильтрующий элемент'),
        ),
    ]
