# Generated by Django 3.2 on 2024-10-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0007_calulaterectanglemodel_finished_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='heating',
            field=models.CharField(blank=True, editable=False, help_text='Подогрев воды в бассейне', max_length=200, verbose_name='Подогрев'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='zaclad_material',
            field=models.CharField(blank=True, editable=False, help_text='Финишная отделка', max_length=200, verbose_name='Материал закладнных'),
        ),
    ]
