# Generated by Django 3.2 on 2024-10-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0009_auto_20241023_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='adding_water_amount',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Количество Автоматический долив воды'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='adding_water_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='Донный слив', max_length=200, verbose_name='Автоматический долив воды'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='adding_water_price',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Цена Автоматический долив воды'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='adding_water_summ',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Сумма за Автоматический долив воды'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='bottom_drain_amount',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Количество донного слива'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='bottom_drain_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='Донный слив', max_length=200, verbose_name='Донный слив'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='bottom_drain_price',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Цена донного слива'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='bottom_drain_summ',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Сумма за донный слив'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='drain_nozzle_amount',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Количество Сливная форсунка'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='drain_nozzle_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='Донный слив', max_length=200, verbose_name='Сливная форсунка'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='drain_nozzle_price',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Цена Сливная форсунка'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='drain_nozzle_summ',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Сумма за Сливная форсунка'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='nozzle_amount',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Количество Форсунка возвратная'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='nozzle_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='Форсунка возвратная', max_length=200, verbose_name='Форсунка возвратная'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='nozzle_price',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Цена Форсунка возвратная'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='nozzle_summ',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Сумма за Форсунка возвратная'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='skimmers_amount',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Количество скиммеров'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='skimmers_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='Скиммер', max_length=200, verbose_name='Скиммер'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='skimmers_price',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Цена скиммера'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='skimmers_summ',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Сумма за скиммеры'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='vacuum_clean_nozzle_amount',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Количество Пылесосная форсунка'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='vacuum_clean_nozzle_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='Донный слив', max_length=200, verbose_name='Пылесосная форсунка'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='vacuum_clean_nozzle_price',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Цена Пылесосная форсунка'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='vacuum_clean_nozzle_summ',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Сумма за Пылесосная форсунка'),
        ),
    ]
