# Generated by Django 3.2 on 2024-10-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0010_alter_calulaterectanglemodel_finished_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='ligth_quantity',
            field=models.IntegerField(blank=True, default=1, editable=False, help_text='Количество ламп', verbose_name='Количество ламп'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='ligthing',
            field=models.CharField(blank=True, editable=False, help_text='Подводное освещение', max_length=200, verbose_name='Освещение'),
        ),
    ]
