# Generated by Django 3.2 on 2024-10-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_ultravioletmodel'),
        ('calculation', '0010_auto_20241025_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='ultraviolet',
            field=models.ForeignKey(blank=True, help_text='Необходимо выбрать максимально приблеженную к мощности насоса', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.ultravioletmodel', verbose_name='UV установка'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='ultraviolet_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Цена UV установки'),
        ),
    ]
