# Generated by Django 3.2 on 2024-10-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0011_auto_20241025_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='valve_amount',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Количество вентилей'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='valve_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=200, verbose_name='Вентильная группа'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='valve_price',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Цена вентиля'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='valve_summ',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Сумма за вентили'),
        ),
    ]
