# Generated by Django 3.2 on 2024-10-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0011_auto_20241017_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='ligth_quantity',
            field=models.IntegerField(blank=True, editable=False, help_text='Количество ламп', null=True, verbose_name='Количество ламп'),
        ),
    ]
