# Generated by Django 3.2 on 2024-10-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0012_auto_20241025_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='desinfection',
            field=models.JSONField(blank=True, editable=False, help_text='Дозирующее оборудование', max_length=200, verbose_name='Дезинфекция'),
        ),
    ]
