# Generated by Django 3.2 on 2024-10-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0013_alter_calulaterectanglemodel_heating'),
    ]

    operations = [
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='cleaner',
            field=models.BooleanField(blank=True, default=False, editable=False, help_text='Подводный пылесос', verbose_name='Пылесос'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='cover',
            field=models.BooleanField(blank=True, default=False, editable=False, help_text='Плавающее покрывало', verbose_name='Покрывало'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='desinfection',
            field=models.CharField(blank=True, editable=False, help_text='Дозирующее оборудование', max_length=200, verbose_name='Дезинфекция'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='pit',
            field=models.BooleanField(blank=True, default=False, editable=False, help_text='Полипропиленовый приямок', verbose_name='Приямок'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='winding',
            field=models.BooleanField(blank=True, default=False, editable=False, help_text='Сматывающее устройство', verbose_name='Сматывающее устройство'),
        ),
    ]
