# Generated by Django 3.2 on 2024-10-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0013_alter_calulaterectanglemodel_desinfection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='desinfection',
            field=models.JSONField(blank=True, editable=False, help_text='Дозирующее оборудование', max_length=2000, verbose_name='Дезинфекция'),
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='heating',
            field=models.JSONField(blank=True, editable=False, help_text='Подогрев воды в бассейне', max_length=2000, null=True, verbose_name='Подогрев'),
        ),
    ]
