# Generated by Django 3.2 on 2024-10-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0014_auto_20241018_1235'),
        ('calculation', '0014_auto_20241018_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='concrete',
            field=models.IntegerField(default=1, editable=False, verbose_name='Бетонные работы'),
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='digging',
            field=models.ForeignKey(default=1, help_text='Выбрать из имеющегося', on_delete=django.db.models.deletion.CASCADE, to='catalogs.diggingmodel', verbose_name='Разработка котлована'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calulaterectanglemodel',
            name='export',
            field=models.ForeignKey(default=1, help_text='Выбрать из имеющегося', on_delete=django.db.models.deletion.CASCADE, to='catalogs.exportmodel', verbose_name='Вывоз грунта'),
            preserve_default=False,
        ),
    ]
