# Generated by Django 3.2 on 2024-10-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0014_auto_20241028_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='ligthing',
            field=models.JSONField(blank=True, editable=False, help_text='Подводное освещение', max_length=2000, verbose_name='Освещение'),
        ),
    ]
