# Generated by Django 3.2 on 2024-10-29 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0020_delete_concretemodel'),
        ('calculation', '0015_alter_calulaterectanglemodel_ligthing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='filter_element',
            field=models.ForeignKey(default=1, help_text='Выбрать из имеющегося', on_delete=django.db.models.deletion.CASCADE, to='catalogs.filterelementmodel', verbose_name='Фильтрующий элемент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='filtration_speed',
            field=models.FloatField(choices=[(30, '30 м/ч'), (20, '20 м/ч'), (10, '10 м/ч')], default=30, help_text='Чем ниже скорость тем качественнее очистка воды', max_length=20, verbose_name='Скорость фильтрации'),
        ),
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='water_exchange_time',
            field=models.FloatField(choices=[(6.0, '6 часов'), (4.0, '4 часа'), (2.0, '2 часа'), (1.0, '1 час'), (0.5, '30 минут')], default=6, help_text='Для частного бассейна необходимо 6 часов, для бассейнов в небольших гостиницах 4 часа', max_length=20, verbose_name='Время полного водообмена'),
        ),
    ]
