# Generated by Django 3.2 on 2024-11-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0016_auto_20241029_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calulaterectanglemodel',
            name='concrete',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Бетонные работы'),
        ),
    ]
