# Generated by Django 3.2 on 2024-10-29 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excavationrequirementsmodel',
            name='bedding_materials',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='construction.inertmaterialsmodel', verbose_name='Материал для подсыпки'),
        ),
        migrations.AlterField(
            model_name='excavationrequirementsmodel',
            name='bedding_thickness',
            field=models.FloatField(blank=True, default=0.0, help_text='в миллиметрах для расчета необходимого количества инертных материалов. (не обязательно)', verbose_name='Толщина подсыпки'),
        ),
        migrations.AlterField(
            model_name='excavationrequirementsmodel',
            name='cell_size',
            field=models.FloatField(blank=True, default=0.0, help_text='в миллиметрах для расчета необходимого количества материалов.', verbose_name='Размер ячейки'),
        ),
        migrations.AlterField(
            model_name='excavationrequirementsmodel',
            name='concrete_materials',
            field=models.ForeignKey(blank=True, default='', help_text='Бетон используемый для отливки стен и основания', on_delete=django.db.models.deletion.CASCADE, to='construction.concretemodel', verbose_name='Марка бетона'),
        ),
        migrations.AlterField(
            model_name='excavationrequirementsmodel',
            name='construction',
            field=models.CharField(choices=[('poly', 'Полипропиленовый бассейн'), ('mosaic', 'Бетонный бассейн с покрытием мозаикой'), ('concrete', 'Бетонный бассейн с покрытием пленкой ПВХ'), ('composite', 'Композитный бассейн'), ('steel', 'Бессейн из нержавеющей стали')], default='concrete', max_length=30, verbose_name='тип бассейна'),
        ),
        migrations.AlterField(
            model_name='excavationrequirementsmodel',
            name='filtration',
            field=models.CharField(choices=[('skimmer', 'Скиммерный бассейн'), ('overflow', 'Переливной бассейн')], default='skimmer', max_length=30, verbose_name='Тип фильтрации'),
        ),
        migrations.AlterField(
            model_name='excavationrequirementsmodel',
            name='footing_materials',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='construction.footingmodel', verbose_name='Материал для подбетонки'),
        ),
        migrations.AlterField(
            model_name='excavationrequirementsmodel',
            name='footing_thickness',
            field=models.FloatField(blank=True, default=0.0, help_text='в миллиметрах для расчета необходимого количества материалов. (не обязательно)', verbose_name='Толщина подбетонки'),
        ),
        migrations.AlterField(
            model_name='excavationrequirementsmodel',
            name='number_of_rows',
            field=models.IntegerField(blank=True, default=0.0, help_text='Для расчета необходимого количества материалов.', verbose_name='Количество рядов '),
        ),
        migrations.AlterField(
            model_name='excavationrequirementsmodel',
            name='reinforcement_diameter',
            field=models.FloatField(blank=True, default=0.0, help_text='в миллиметрах.', verbose_name='Диаметр арматуры'),
        ),
    ]
