# Generated by Django 3.2 on 2024-10-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermodel',
            name='manager',
            field=models.CharField(blank=True, help_text='Имя персонального менеджера', max_length=200, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='name',
            field=models.CharField(help_text='Название основного поставщика', max_length=200, verbose_name='Поставщик'),
        ),
    ]
