# Generated by Django 5.1.3 on 2024-11-19 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Контактный номер телефона', max_length=20, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=200, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Номера телефонов компании',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False, verbose_name='Использовать по умолчанию')),
                ('name', models.CharField(help_text='Коммерческое название компании', max_length=200, verbose_name='Название')),
                ('legal_name', models.CharField(help_text='ООО или ИП', max_length=200, verbose_name='Юридическое название')),
                ('inn', models.IntegerField(help_text='ИНН', verbose_name='ИНН')),
                ('ogrn', models.IntegerField(help_text='ОГРН', verbose_name='ОГРН')),
                ('post_address', models.TextField(help_text='Для договора', verbose_name='Юридиченский адрес')),
                ('physical_address', models.TextField(help_text='Для договора', verbose_name='Фактический адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('web_site', models.CharField(blank=True, default='', help_text='при наличии', max_length=200, verbose_name='Веб сайт')),
                ('logotype', models.ImageField(help_text='Без заднего фона', upload_to='company/logotype/', verbose_name='Логотип компании ')),
                ('personal', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('phone', models.ManyToManyField(help_text='Контактный номер телефона', to='login.phones', verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Насос',
                'verbose_name_plural': 'Насосное оборудование',
            },
        ),
    ]
