# Generated by Django 3.2 on 2024-10-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя клиента', max_length=200, verbose_name='ФИО')),
                ('city', models.CharField(help_text='Город строительства', max_length=200, verbose_name='Город строительства')),
                ('phone', models.CharField(help_text='Номер телефона клиента', max_length=50, verbose_name='Номер телефона клиента')),
                ('email', models.EmailField(blank=True, help_text='Не обязательно. На указанный адрес автоматически отправится расчет', max_length=254, verbose_name='Электронная почта')),
                ('note', models.TextField(blank=True, help_text='Любая информация которая может пригодится. Н обязательно к заполнению', verbose_name='Заметка')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты компании',
            },
        ),
    ]
