# Generated by Django 3.2 on 2024-10-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='send_calculation',
            field=models.BooleanField(default=False, help_text='Используется для ', verbose_name='Отправить расчет'),
        ),
    ]
