# Generated by Django 3.2 on 2024-10-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientmodel_send_calculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='send_calculation',
        ),
    ]
