# Generated by Django 3.2 on 2024-10-07 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='В точности как в каталоге поставщика', max_length=500, verbose_name='Номенклатура')),
                ('article', models.CharField(help_text='В точности как в каталоге поставщика', max_length=100, verbose_name='Артикул')),
                ('square', models.IntegerField(blank=True, default=0.0, help_text='Из каталога поставщика. В мм', null=True, verbose_name='Диаметр')),
                ('filter', models.FloatField(blank=True, default=0.0, help_text='Из каталога поставщика. в м2', null=True, verbose_name='Площадь фильтрации')),
                ('sand', models.IntegerField(blank=True, default=0.0, help_text='Из каталога поставщика. В кг', null=True, verbose_name='количество фильтрата')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Розничная стоимость')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Дата актуальности цены', null=True, verbose_name='Дата')),
                ('image', models.ImageField(help_text='Красивое фото используется для оформления обложки страницы с описанием услуги', upload_to='catalog/product/', verbose_name='Фото товара')),
                ('status', models.CharField(default='no_found', editable=False, max_length=50)),
                ('product_url', models.URLField(blank=True, help_text='Заполняется автоматически', null=True, verbose_name='Ссылка на товар у поставщика')),
                ('supplier', models.ForeignKey(help_text='Выбрать из поставщиков', on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Фильтра',
                'verbose_name_plural': 'Фильтровальное оборудование',
            },
        ),
    ]
