# Generated by Django 3.2 on 2024-10-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtermodel',
            name='valve',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Тип вентиля'),
        ),
    ]
