# Generated by Django 3.2 on 2024-10-08 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20241007_1611'),
        ('catalogs', '0002_auto_20241007_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtermodel',
            name='image',
            field=models.ImageField(help_text='Красивое фото используется для оформления обложки страницы с описанием услуги', upload_to='catalog/filters/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='filtermodel',
            name='product_url',
            field=models.URLField(blank=True, help_text='Для актуализации цен в каталоге поставщика. ', null=True, verbose_name='Ссылка на товар у поставщика'),
        ),
        migrations.AlterField(
            model_name='pumpsmodel',
            name='image',
            field=models.ImageField(help_text='Красивое фото используется для оформления обложки страницы с описанием услуги', upload_to='catalog/pumps/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='pumpsmodel',
            name='product_url',
            field=models.URLField(blank=True, help_text='Для актуализации цен в каталоге поставщика. ', null=True, verbose_name='Ссылка на товар у поставщика'),
        ),
        migrations.CreateModel(
            name='FinishingMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='В точности как в каталоге поставщика', max_length=500, verbose_name='Номенклатура')),
                ('article', models.CharField(blank=True, help_text='В точности как в каталоге поставщика', max_length=100, verbose_name='Артикул')),
                ('type_materials', models.CharField(blank=True, choices=[('poly', 'Полипропилен'), ('pvh', 'Пленка ПВХ')], default='pvh', help_text='Пленка ПВХ / Полипропилен', max_length=20, null=True, verbose_name='Категория материала')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Розничная стоимость за м2')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Дата актуальности цены', null=True, verbose_name='Дата')),
                ('image', models.ImageField(help_text='Красивое фото используется для оформления обложки страницы с описанием услуги', upload_to='catalog/finished/', verbose_name='Фото товара')),
                ('status', models.CharField(default='no_found', editable=False, max_length=50)),
                ('product_url', models.URLField(blank=True, help_text='Для актуализации цен в каталоге поставщика. ', null=True, verbose_name='Ссылка на товар у поставщика')),
                ('supplier', models.ForeignKey(help_text='Выбрать из поставщиков', on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Отделочные материалы',
            },
        ),
    ]
