# Generated by Django 3.2 on 2024-10-08 12:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20241007_1611'),
        ('catalogs', '0004_auto_20241008_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtermodel',
            name='image',
            field=models.ImageField(help_text='Красивое фото используется для коммерческого предложения', upload_to='catalog/filters/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='finishingmaterialsmodel',
            name='image',
            field=models.ImageField(help_text='Красивое фото используется для коммерческого предложения', upload_to='catalog/finished/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='pumpsmodel',
            name='image',
            field=models.ImageField(help_text='Красивое фото используется для коммерческого предложения', upload_to='catalog/pumps/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='zacladmodel',
            name='image',
            field=models.ImageField(help_text='Красивое фото используется для коммерческого предложения', upload_to='catalog/zaclad/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='zacladmodel',
            name='type_materials',
            field=models.CharField(blank=True, choices=[('abs', 'ABS пластик'), ('aisi', 'AISI-316 нержавеющий металл')], default='abs', help_text='Пластик или нерж', max_length=20, null=True, verbose_name='Материал изготовления'),
        ),
        migrations.AlterField(
            model_name='zacladmodel',
            name='type_zaclad',
            field=models.CharField(blank=True, choices=[('scimmer', 'Скиммер'), ('forsunka', 'Возвратная фрсунка'), ('sliv', 'Донный слив'), ('doliv', 'Долив воды'), ('polusos', 'Пылесос')], help_text='Выбрать подходящее', max_length=20, null=True, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='LightingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='В точности как в каталоге поставщика', max_length=500, verbose_name='Номенклатура')),
                ('article', models.CharField(blank=True, help_text='В точности как в каталоге поставщика', max_length=100, verbose_name='Артикул')),
                ('type_category', models.CharField(blank=True, choices=[('lamp', 'Лампа'), ('flask', 'Прожектор без лампы'), ('overlay', 'Лицевая панель'), ('automation', 'Автоматика управления')], help_text='Выбрать подходящее', max_length=20, null=True, verbose_name='Категория')),
                ('type_lighting', models.CharField(blank=True, choices=[('white', 'Белый свет'), ('rgb', 'RGB'), ('none', 'НЕТ (Для закладной и автоматики)')], help_text='Выбрать подходящее', max_length=20, null=True, verbose_name='Цвет свечения')),
                ('type_materials', models.CharField(blank=True, choices=[('abs', 'ABS пластик'), ('aisi', 'AISI-316 нержавеющий металл')], default='abs', help_text='Пластик или нерж', max_length=20, null=True, verbose_name='Материал изготовления')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Розничная стоимость за ед.')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Дата актуальности цены', null=True, verbose_name='Дата')),
                ('image', models.ImageField(help_text='Красивое фото используется для коммерческого предложения', upload_to='catalog/light/', verbose_name='Фото товара')),
                ('status', models.CharField(default='no_found', editable=False, max_length=50)),
                ('product_url', models.URLField(blank=True, help_text='Для актуализации цен в каталоге поставщика. ', null=True, verbose_name='Ссылка на товар у поставщика')),
                ('supplier', models.ForeignKey(help_text='Выбрать из поставщиков', on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Закладную',
                'verbose_name_plural': 'Закладные',
            },
        ),
    ]
