# Generated by Django 3.2 on 2024-10-23 13:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('catalogs', '0006_alter_additionalmaterial_type_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterElementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='')),
                ('quantity_per_unit', models.FloatField(blank=True, default=0, null=True, verbose_name='количество в единице')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Розничная стоимость')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Дата актуальности цены', null=True, verbose_name='Дата')),
                ('status', models.CharField(default='no_found', editable=False, max_length=50)),
                ('product_url', models.URLField(blank=True, help_text='Для актуализации цен в каталоге поставщика. ', null=True, verbose_name='Ссылка на товар у поставщика')),
                ('supplier', models.ForeignKey(help_text='Выбрать из поставщиков', on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Номенклатуру',
                'verbose_name_plural': 'Фильтрующий элемент',
            },
        ),
    ]
