# Generated by Django 3.2 on 2024-10-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_filterelementmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterelementmodel',
            name='name',
            field=models.CharField(help_text='Номенклатурное наименование', max_length=200, verbose_name='Наименование'),
        ),
    ]
