# Generated by Django 3.2 on 2024-10-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_auto_20241017_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setdesinfectionmodelrx',
            old_name='phliquid_liquid_price',
            new_name='ph_liquid_price',
        ),
    ]
