# Generated by Django 3.2 on 2024-10-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_alter_filterelementmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zacladmodel',
            name='type_zaclad',
            field=models.CharField(blank=True, choices=[('skimmer', 'Скиммер'), ('nozzle', 'Возвратная фрсунка'), ('bottom_drain', 'Донный слив'), ('adding_water', 'Долив воды автоматический'), ('vacuum_clean_nozzle', 'Дополнительная форсунка для подключения пылесоса'), ('drain_nozzle', 'Форсунка для слива воды')], help_text='Выбрать подходящее', max_length=20, null=True, verbose_name='Категория'),
        ),
    ]
