# Generated by Django 3.2 on 2024-10-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_auto_20241017_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setdesinfectionmodelcl',
            old_name='rx_article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='setdesinfectionmodelcl',
            old_name='rx_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='setdesinfectionmodelcl',
            old_name='rx_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='setdesinfectionmodelcl',
            old_name='rx_product_url',
            new_name='product_url',
        ),
        migrations.RenameField(
            model_name='setdesinfectionmodelcl',
            old_name='rx_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='setdesinfectionmodelcl',
            name='rx_name',
        ),
    ]
