# Generated by Django 3.2 on 2024-10-25 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('catalogs', '0009_alter_zacladmodel_type_zaclad'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltravioletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='В точности как в каталоге поставщика', max_length=500, verbose_name='Номенклатура')),
                ('article', models.CharField(blank=True, help_text='В точности как в каталоге поставщика', max_length=100, verbose_name='Артикул')),
                ('power', models.FloatField(blank=True, default=0.0, help_text='Из каталога поставщика. В м3/ч', null=True, verbose_name='Мощность')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Розничная стоимость')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Дата актуальности цены', null=True, verbose_name='Дата')),
                ('image', models.ImageField(blank=True, help_text='Красивое фото используется для коммерческого предложения', upload_to='catalog/pumps/', verbose_name='Фото товара')),
                ('status', models.CharField(default='no_found', editable=False, max_length=50)),
                ('product_url', models.URLField(blank=True, help_text='Для актуализации цен в каталоге поставщика. ', null=True, verbose_name='Ссылка на товар у поставщика')),
                ('supplier', models.ForeignKey(blank=True, help_text='Выбрать из поставщиков', on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Насос',
                'verbose_name_plural': 'Насосное оборудование',
            },
        ),
    ]
