# Generated by Django 3.2 on 2024-10-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_auto_20241017_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='setdesinfectionmodelrx',
            name='model_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
