# Generated by Django 3.2 on 2024-10-25 10:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('catalogs', '0010_ultravioletmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filtermodel',
            options={'verbose_name': 'Вентиль', 'verbose_name_plural': 'Вентильная группа'},
        ),
        migrations.AlterModelOptions(
            name='ultravioletmodel',
            options={'verbose_name': 'УФ установку', 'verbose_name_plural': 'УФ установка'},
        ),
        migrations.RemoveField(
            model_name='filtermodel',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='filtermodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='filtermodel',
            name='sand',
        ),
        migrations.RemoveField(
            model_name='filtermodel',
            name='square',
        ),
        migrations.AddField(
            model_name='filtermodel',
            name='connection_diameter',
            field=models.IntegerField(default=0.0, null=True, verbose_name='Диаметр подключения'),
        ),
        migrations.AlterField(
            model_name='filtermodel',
            name='article',
            field=models.CharField(blank=True, help_text='В точности как в каталоге поставщика', max_length=100, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='filtermodel',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Выбрать из поставщиков', on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='filtermodel',
            name='valve',
            field=models.CharField(choices=[('automatic', 'Автоматический вентиль'), ('manual', 'Ручной вентиль')], default='manual', max_length=20, verbose_name='Тип вентиля'),
        ),
        migrations.CreateModel(
            name='ValveGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='В точности как в каталоге поставщика', max_length=500, verbose_name='Номенклатура')),
                ('article', models.CharField(help_text='В точности как в каталоге поставщика', max_length=100, verbose_name='Артикул')),
                ('square', models.IntegerField(blank=True, default=0.0, help_text='Из каталога поставщика. В мм', null=True, verbose_name='Диаметр')),
                ('filter', models.FloatField(blank=True, default=0.0, help_text='Из каталога поставщика. в м2', null=True, verbose_name='Площадь фильтрации')),
                ('sand', models.IntegerField(blank=True, default=0.0, help_text='Из каталога поставщика. В кг', null=True, verbose_name='количество фильтрата')),
                ('valve', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Тип вентиля')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Розничная стоимость')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Дата актуальности цены', null=True, verbose_name='Дата')),
                ('image', models.ImageField(help_text='Красивое фото используется для коммерческого предложения', upload_to='catalog/filters/', verbose_name='Фото товара')),
                ('status', models.CharField(default='no_found', editable=False, max_length=50)),
                ('product_url', models.URLField(blank=True, help_text='Для актуализации цен в каталоге поставщика. ', null=True, verbose_name='Ссылка на товар у поставщика')),
                ('supplier', models.ForeignKey(help_text='Выбрать из поставщиков', on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтровальное оборудование',
            },
        ),
    ]
