# Generated by Django 3.2 on 2024-10-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0011_setdesinfectionmodelrx_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrolysismodel',
            name='model_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='setdesinfectionmodelcl',
            name='model_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
