# Generated by Django 3.2 on 2024-10-25 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('catalogs', '0011_auto_20241025_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filtermodel',
            options={'verbose_name': 'Фильтр', 'verbose_name_plural': 'Фильтровальное оборудование'},
        ),
        migrations.AlterModelOptions(
            name='valvegroupmodel',
            options={'verbose_name': 'Вентиль', 'verbose_name_plural': 'Вентильная группа'},
        ),
        migrations.RemoveField(
            model_name='filtermodel',
            name='connection_diameter',
        ),
        migrations.RemoveField(
            model_name='valvegroupmodel',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='valvegroupmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='valvegroupmodel',
            name='sand',
        ),
        migrations.RemoveField(
            model_name='valvegroupmodel',
            name='square',
        ),
        migrations.AddField(
            model_name='filtermodel',
            name='filter',
            field=models.FloatField(blank=True, default=0.0, help_text='Из каталога поставщика. в м2', null=True, verbose_name='Площадь фильтрации'),
        ),
        migrations.AddField(
            model_name='filtermodel',
            name='image',
            field=models.ImageField(default=1, help_text='Красивое фото используется для коммерческого предложения', upload_to='catalog/filters/', verbose_name='Фото товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filtermodel',
            name='sand',
            field=models.IntegerField(blank=True, default=0.0, help_text='Из каталога поставщика. В кг', null=True, verbose_name='количество фильтрата'),
        ),
        migrations.AddField(
            model_name='filtermodel',
            name='square',
            field=models.IntegerField(blank=True, default=0.0, help_text='Из каталога поставщика. В мм', null=True, verbose_name='Диаметр'),
        ),
        migrations.AddField(
            model_name='valvegroupmodel',
            name='connection_diameter',
            field=models.IntegerField(default=0.0, null=True, verbose_name='Диаметр подключения'),
        ),
        migrations.AlterField(
            model_name='filtermodel',
            name='article',
            field=models.CharField(help_text='В точности как в каталоге поставщика', max_length=100, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='filtermodel',
            name='supplier',
            field=models.ForeignKey(help_text='Выбрать из поставщиков', on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='filtermodel',
            name='valve',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Тип вентиля'),
        ),
        migrations.AlterField(
            model_name='valvegroupmodel',
            name='article',
            field=models.CharField(blank=True, help_text='В точности как в каталоге поставщика', max_length=100, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='valvegroupmodel',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Выбрать из поставщиков', on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='valvegroupmodel',
            name='valve',
            field=models.CharField(choices=[('automatic', 'Автоматический вентиль'), ('manual', 'Ручной вентиль')], default='manual', max_length=20, verbose_name='Тип вентиля'),
        ),
    ]
