# Generated by Django 3.2 on 2024-10-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0012_auto_20241025_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvegroupmodel',
            name='connection_type',
            field=models.CharField(choices=[('automatic', 'Автоматический вентиль'), ('manual', 'Ручной вентиль')], default='manual', max_length=20, verbose_name='Тип вентиля'),
        ),
        migrations.AlterField(
            model_name='valvegroupmodel',
            name='connection_diameter',
            field=models.FloatField(default=0.0, null=True, verbose_name='Диаметр подключения'),
        ),
        migrations.AlterField(
            model_name='valvegroupmodel',
            name='valve',
            field=models.CharField(choices=[('lateral', 'Боковое подключение'), ('upper', 'Верхнее подключение')], default='upper', max_length=20, verbose_name='Тип подключения'),
        ),
    ]
