# Generated by Django 3.2 on 2024-10-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0013_auto_20241025_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtermodel',
            name='connection_type',
            field=models.CharField(choices=[('lateral', 'Боковое подключение'), ('upper', 'Верхнее подключение')], default='upper', max_length=20, verbose_name='Тип подключения'),
        ),
    ]
