# Generated by Django 3.2 on 2024-10-28 06:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('catalogs', '0014_filtermodel_connection_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEquipmentHeatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='В точности как в каталоге поставщика', max_length=500, verbose_name='Номенклатура')),
                ('type_category', models.CharField(blank=True, choices=[('electro', 'Электронагреватель'), ('warm', 'Теплообменник'), ('pump', 'Тепловой насос')], help_text='Выбрать подходящее', max_length=20, null=True, verbose_name='Категория')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Розничная стоимость за ед.')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Дата актуальности цены', null=True, verbose_name='Дата')),
                ('status', models.CharField(default='no_found', editable=False, max_length=50)),
                ('product_url', models.URLField(blank=True, help_text='Для актуализации цен в каталоге поставщика. ', null=True, verbose_name='Ссылка на товар у поставщика')),
                ('supplier', models.ForeignKey(blank=True, help_text='Выбрать из поставщиков', null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Номенклатуру',
                'verbose_name_plural': 'Комплектующие для подогрева воды',
            },
        ),
        migrations.AddField(
            model_name='heatingmodel',
            name='additional_equipment',
            field=models.ManyToManyField(blank=True, default='', help_text='Выбрать необходимое оборудование', null=True, to='catalogs.AdditionalEquipmentHeatingModel', verbose_name='Комплектующие для подключения'),
        ),
    ]
