# Generated by Django 3.2 on 2024-10-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0015_auto_20241028_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatingmodel',
            name='additional_equipment',
            field=models.ManyToManyField(blank=True, default='', help_text='Выбрать необходимое оборудование', to='catalogs.AdditionalEquipmentHeatingModel', verbose_name='Комплектующие для подключения'),
        ),
    ]
