# Generated by Django 3.2 on 2024-10-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0016_alter_heatingmodel_additional_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightingmodel',
            name='power',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='lightingmodel',
            name='type_lighting',
            field=models.CharField(blank=True, choices=[('white', 'Белый свет'), ('rgb', 'RGB'), ('transformer', 'Трансформатор'), ('none', 'НЕТ (Для закладной и автоматики)')], help_text='Выбрать подходящее', max_length=20, null=True, verbose_name='Цвет свечения'),
        ),
    ]
