# Generated by Django 3.2 on 2024-10-28 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('catalogs', '0017_auto_20241028_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingAdittionalMaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='В точности как в каталоге поставщика', max_length=500, verbose_name='Номенклатура')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Розничная стоимость за ед.')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Дата актуальности цены', null=True, verbose_name='Дата')),
                ('status', models.CharField(default='no_found', editable=False, max_length=50)),
                ('product_url', models.URLField(blank=True, help_text='Для актуализации цен в каталоге поставщика. ', null=True, verbose_name='Ссылка на товар у поставщика')),
                ('supplier', models.ForeignKey(blank=True, help_text='Выбрать из поставщиков', null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Номенклатуру',
                'verbose_name_plural': 'Комплектующие для подводного освещения',
            },
        ),
        migrations.CreateModel(
            name='LightingAutomationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='В точности как в каталоге поставщика', max_length=500, verbose_name='Номенклатура')),
                ('article', models.CharField(blank=True, help_text='В точности как в каталоге поставщика', max_length=100, verbose_name='Артикул')),
                ('power', models.IntegerField(blank=True, default=0, null=True, verbose_name='Мощность')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Розничная стоимость за ед.')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Дата актуальности цены', null=True, verbose_name='Дата')),
                ('status', models.CharField(default='no_found', editable=False, max_length=50)),
                ('product_url', models.URLField(blank=True, help_text='Для актуализации цен в каталоге поставщика. ', null=True, verbose_name='Ссылка на товар у поставщика')),
                ('supplier', models.ForeignKey(blank=True, help_text='Выбрать из поставщиков', on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Номенклатуру',
                'verbose_name_plural': 'Автоматика управления освещением',
            },
        ),
        migrations.CreateModel(
            name='LightingFlaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='В точности как в каталоге поставщика', max_length=500, verbose_name='Номенклатура')),
                ('article', models.CharField(blank=True, help_text='В точности как в каталоге поставщика', max_length=100, verbose_name='Артикул')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Розничная стоимость за ед.')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Дата актуальности цены', null=True, verbose_name='Дата')),
                ('status', models.CharField(default='no_found', editable=False, max_length=50)),
                ('product_url', models.URLField(blank=True, help_text='Для актуализации цен в каталоге поставщика. ', null=True, verbose_name='Ссылка на товар у поставщика')),
                ('supplier', models.ForeignKey(blank=True, help_text='Выбрать из поставщиков', on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Номенклатуру',
                'verbose_name_plural': 'Подводный светильник без лампы',
            },
        ),
        migrations.CreateModel(
            name='LightingLampModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='В точности как в каталоге поставщика', max_length=500, verbose_name='Номенклатура')),
                ('article', models.CharField(blank=True, help_text='В точности как в каталоге поставщика', max_length=100, verbose_name='Артикул')),
                ('type_lighting', models.CharField(blank=True, choices=[('white', 'Белый свет'), ('rgb', 'RGB')], help_text='Выбрать подходящее', max_length=20, null=True, verbose_name='Цвет свечения')),
                ('power', models.IntegerField(blank=True, default=0, null=True, verbose_name='Мощность')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Розничная стоимость за ед.')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Дата актуальности цены', null=True, verbose_name='Дата')),
                ('status', models.CharField(default='no_found', editable=False, max_length=50)),
                ('product_url', models.URLField(blank=True, help_text='Для актуализации цен в каталоге поставщика. ', null=True, verbose_name='Ссылка на товар у поставщика')),
                ('supplier', models.ForeignKey(blank=True, help_text='Выбрать из поставщиков', on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Номенклатуру',
                'verbose_name_plural': 'Лампа подводного освещения',
            },
        ),
        migrations.CreateModel(
            name='LightingSetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_materials', models.CharField(blank=True, choices=[('abs', 'Пластик'), ('aisi', 'Нержавейка')], default='abs', help_text='Пластик или нерж', max_length=20, null=True, verbose_name='Материал изготовления')),
                ('type_lighting', models.CharField(blank=True, choices=[('white', 'Белый свет'), ('rgb', 'RGB')], help_text='Выбрать подходящее', max_length=20, null=True, verbose_name='Цвет свечения')),
                ('additional_materials', models.ManyToManyField(blank=True, help_text='Дополнительные материалы для подводного освещения', to='catalogs.LightingAdittionalMaterialModel', verbose_name='Дополнительные материалы')),
                ('flask', models.ForeignKey(help_text='Подводный светильник', on_delete=django.db.models.deletion.CASCADE, to='catalogs.lightingflaskmodel', verbose_name='Закладная')),
                ('lamp', models.ForeignKey(help_text='Лампа для подводного освещения', on_delete=django.db.models.deletion.CASCADE, to='catalogs.lightinglampmodel', verbose_name='Лампа')),
            ],
            options={
                'verbose_name': 'Номенклатуру',
                'verbose_name_plural': 'Комплект подводного освещения',
            },
        ),
        migrations.CreateModel(
            name='LightingTransformerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='В точности как в каталоге поставщика', max_length=500, verbose_name='Номенклатура')),
                ('article', models.CharField(blank=True, help_text='В точности как в каталоге поставщика', max_length=100, verbose_name='Артикул')),
                ('power', models.IntegerField(blank=True, default=0, null=True, verbose_name='Мощность')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Розничная стоимость за ед.')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Дата актуальности цены', null=True, verbose_name='Дата')),
                ('status', models.CharField(default='no_found', editable=False, max_length=50)),
                ('product_url', models.URLField(blank=True, help_text='Для актуализации цен в каталоге поставщика. ', null=True, verbose_name='Ссылка на товар у поставщика')),
                ('supplier', models.ForeignKey(blank=True, help_text='Выбрать из поставщиков', on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Номенклатуру',
                'verbose_name_plural': 'Понижающий трансформатор',
            },
        ),
        migrations.DeleteModel(
            name='LightingModel',
        ),
    ]
