# Generated by Django 3.2 on 2024-10-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0018_auto_20241028_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightingsetmodel',
            name='name',
            field=models.CharField(default=1, help_text='В точности как в каталоге поставщика', max_length=500, verbose_name='Номенклатура'),
            preserve_default=False,
        ),
    ]
