# Generated by Django 3.2 on 2024-10-29 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0019_lightingsetmodel_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConcreteModel',
        ),
    ]
